export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESSFUL = 'USER_SIGN_UP_SUCCESSFUL';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESSFUL = 'USER_SIGNIN_SUCCESSFUL';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const CLEAR_ALL = "CLEAR_ALL";