export const CALL_REQUEST =  "CALL_REQUEST";
export const CALL_FAILED = "CALL_FAILED";
export const CALL_IN_PROGRESS = "CALL_IN_PROGRESS";
export const CALL_CONNECTED = "CALL_CONNECTED";
export const CALL_DISCONNECTED = "CALL_DISCONNECTED";
export const CALL_RESET = "CALL_RESET";
export const CALL_LOG_REQUEST = "CALL_LOG_REQUEST";
export const CALL_LOG_SUCCESSFUL = "CALL_LOG_SUCCESSFUL";
export const CALL_LOG_FAILED = "CALL_LOG_FAILED";
export const CALL_LOG_RESET = "CALL_LOG_RESET";
export const CALL_UPDATE_LOG_REQUEST = "CALL_UPDATE_LOG_REQUEST";
export const CALL_UPDATE_LOG_SUCCESSFUL = "CALL_UPDATE_LOG_SUCCESSFUL";
export const CALL_UPDATE_LOG_FAILED = "CALL_UPDATE_LOG_FAILED";


export const CALL_CANCELED_REQUEST = "CALL_CANCELED_REQUEST";
export const CALL_CANCELED_SUCCESSFUL = "CALL_CANCELED_SUCCESSFUL";
export const CALL_CANCELED_FAILED = "CALL_CANCELED_FAILED";

export const CONTACT_SAVE_REQUEST = "CONTACT_SAVE_REQUEST";
export const CONTACT_SAVE_SUCCESSFUL = "CONTACT_SAVE_SUCCESSFUL";
export const CONTACT_SAVE_FAILED = "CONTACT_SAVE_FAILED";

export const CONTACT_EDIT_REQUEST = "CONTACT_EDIT_REQUEST";
export const CONTACT_EDIT_SUCCESSFUL = "CONTACT_EDIT_SUCCESSFUL";
export const CONTACT_EDIT_FAILED = "CONTACT_EDIT_FAILED";

export const CONTACT_REMOVE_REQUEST = "CONTACT_REMOVE_REQUEST";
export const CONTACT_REMOVE_SUCCESSFUL = "CONTACT_REMOVE_SUCCESSFUL";
export const CONTACT_REMOVE_FAILED = "CONTACT_REMOVE_FAILED";
export const CONTACT_SAVE_RESET = "CONTACT_SAVE_RESET";

export const CONTACT_LIST_REQUEST = "CONTACT_LIST_REQUEST";
export const CONTACT_LIST_SUCCESSFUL = "CONTACT_LIST_SUCCESSFUL";
export const CONTACT_LIST_FAILED = "CONTACT_LIST_FAILED";

export const CONTACT_DETAIL_REQUEST = "CONTACT_DETAIL_REQUEST";
export const CONTACT_DETAIL_SUCCESSFUL = "CONTACT_DETAIL_SUCCESSFUL";
export const CONTACT_DETAIL_FAILED = "CONTACT_DETAIL_FAILED";

export const HISTORY_LIST_REQUEST = "HISTORY_LIST_REQUEST";
export const HISTORY_LIST_SUCCESSFUL = "HISTORY_LIST_SUCCESSFUL";
export const HISTORY_LIST_FAILED = "HISTORY_LIST_FAILED";

export const CONTACT_SEARCH_REQUEST = "CONTACT_SEARCH_REQUEST";
export const CONTACT_SEARCH_SUCCESSFUL = "CONTACT_SEARCH_SUCCESSFUL";
export const CONTACT_SEARCH_FAILED = "CONTACT_SEARCH_FAILED";
