export const CART_ADDED_ITEM = 'CART_ADDED_ITEM';
export const CART_ADDED_ITEM_FAILED = 'CART_ADDED_ITEM_FAILED';
export const CART_REMOVED_ITEM = 'CART_REMOVED_ITEM';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_EMPTY = 'CART_EMPTY';