export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESSFUL = 'CATEGORY_LIST_SUCCESSFUL';
export const CATEGORY_LIST_FAILED = 'CATEGORY_LIST_FAILED';
export const CATEGORY_LIST_RESET = 'CATEGORY_LIST_RESET';
