export const DRINK_LIST_REQUEST = 'DRINK_LIST_REQUEST';
export const DRINK_LIST_SUCCESSFUL = 'DRINK_LIST_SUCCESSFUL';
export const DRINK_LIST_FAILED = 'DRINK_LIST_FAILED';

export const DRINK_DETAIL_REQUEST = 'DRINK_DETAIL_REQUEST';
export const DRINK_DETAIL_SUCCESSFUL = 'DRINK_DETAIL_SUCCESSFUL';
export const DRINK_DETAIL_FAILED = 'DRINK_DETAIL_FAILED';