export const FEEDBACK_LIST_REQUEST = 'FEEDBACK_LIST_REQUEST';
export const FEEDBACK_LIST_SUCCESSFUL = 'FEEDBACK_LIST_SUCCESSFUL';
export const FEEDBACK_LIST_FAILED = 'FEEDBACK_LIST_FAILED';

export const USER_FEEDBACK_LIST_REQUEST = 'USER_FEEDBACK_LIST_REQUEST';
export const USER_FEEDBACK_LIST_SUCCESSFUL = 'USER_FEEDBACK_LIST_SUCCESSFUL';
export const USER_FEEDBACK_LIST_FAILED = 'USER_FEEDBACK_LIST_FAILED';