export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESSFUL = 'IMAGE_LIST_SUCCESSFUL';
export const IMAGE_LIST_FAILED = 'IMAGE_LIST_FAILED';

export const USER_IMAGE_LIST_REQUEST = 'USER_IMAGE_LIST_REQUEST';
export const USER_IMAGE_LIST_SUCCESSFUL = 'USER_IMAGE_LIST_SUCCESSFUL';
export const USER_IMAGE_LIST_FAILED = 'USER_IMAGE_LIST_FAILED';