
export const ADD_NOTIFICATION_REQUEST = 'ADD_NOTIFICATION_REQUEST';
export const ADD_NOTIFICATION_SUCCESSFUL = 'ADD_NOTIFICATION_SUCCESSFUL';
export const ADD_NOTIFICATION_FAILED = 'ADD_NOTIFICATION_FAILED';

export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESSFUL = 'NOTIFICATION_LIST_SUCCESSFUL';
export const NOTIFICATION_LIST_FAILED = 'NOTIFICATION_LIST_FAILED';

export const EDIT_NOTIFICATION_REQUEST = 'EDIT_NOTIFICATION_REQUEST';
export const EDIT_NOTIFICATION_SUCCESSFUL = 'EDIT_NOTIFICATION_SUCCESSFUL';
export const EDIT_NOTIFICATION_FAILED = 'EDIT_NOTIFICATION_FAILED';

export const ALL_NOTIFICATION_LIST_REQUEST = 'ALL_NOTIFICATION_LIST_REQUEST';
export const ALL_NOTIFICATION_LIST_SUCCESSFUL = 'ALL_NOTIFICATION_LIST_SUCCESSFUL';
export const ALL_NOTIFICATION_LIST_FAILED = 'ALL_NOTIFICATION_LIST_FAILED';