
export const ADD_NOTIFICATION_REQUEST = 'ADD_NOTIFICATION_REQUEST';
export const ADD_NOTIFICATION_SUCCESSFUL = 'ADD_NOTIFICATION_SUCCESSFUL';
export const ADD_NOTIFICATION_FAILED = 'ADD_NOTIFICATION_FAILED';

export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESSFUL = 'NOTIFICATION_LIST_SUCCESSFUL';
export const NOTIFICATION_LIST_FAILED = 'NOTIFICATION_LIST_FAILED';