export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESSFUL = 'CREATE_POST_SUCCESSFUL';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESSFUL = 'EDIT_POST_SUCCESSFUL';
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESSFUL = 'DELETE_POST_SUCCESSFUL';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const CREATE_POST_COMMENT_REQUEST = 'CREATE_POST_COMMENT_REQUEST';
export const CREATE_POST_COMMENT_SUCCESSFUL = 'CREATE_POST_COMMENT_SUCCESSFUL';
export const CREATE_POST_COMMENT_FAILED = 'CREATE_POST_COMMENT_FAILED';

export const EDIT_POST_COMMENT_REQUEST = 'EDIT_POST_COMMENT_REQUEST';
export const EDIT_POST_COMMENT_SUCCESSFUL = 'EDIT_POST_COMMENT_SUCCESSFUL';
export const EDIT_POST_COMMENT_FAILED = 'EDIT_POST_COMMENT_FAILED';

export const DELETE_POST_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_POST_COMMENT_SUCCESSFUL = 'DELETE_COMMENT_SUCCESSFUL';
export const DELETE_POST_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const SHOW_POST_REQUEST = 'SHOW_POST_REQUEST';
export const SHOW_POST_SUCCESSFUL = 'SHOW_POST_SUCCESSFUL';
export const SHOW_POST_FAILED = 'SHOW_POST_FAILED';

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST';
export const POST_DETAILS_SUCCESSFUL = 'POST_DETAILS_SUCCESSFUL';
export const POST_DETAILS_FAILED = 'POST_DETAILS_FAILED';

export const SEARCH_POST_REQUEST = 'SEARCH_POST_REQUEST';
export const SEARCH_POST_SUCCESSFUL = 'SEARCH_POST_SUCCESSFUL';
export const SEARCH_POST_FAILED = 'SEARCH_POST_FAILED';

export const FILTER_TOPIC_REQUEST = 'FILTER_TOPIC_REQUEST';
export const FILTER_TOPIC_SUCCESSFUL = 'FILTER_TOPIC_SUCCESSFUL';
export const FILTER_TOPIC_FAILED = 'FILTER_TOPIC_FAILED';

export const SORT_POST_REQUEST = 'SORT_POST_REQUEST';
export const SORT_POST_SUCCESSFUL = 'SORT_POST_SUCCESSFUL';
export const SORT_POST_FAILED = 'SORT_POST_FAILED';

export const POST_ADD_KEYWORD_REQUEST = "POST_ADD_KEYWORD_REQUEST";
export const POST_ADD_KEYWORD_SUCCESSFUL = "POST_ADD_KEYWORD_SUCCESSFUL";
export const POST_ADD_KEYWORD_FAILED = "POST_ADD_KEYWORD_FAILED";

export const POST_REMOVE_KEYWORD_REQUEST = "POST_REMOVE_KEYWORD_REQUEST";
export const POST_REMOVE_KEYWORD_SUCCESSFUL = "POST_REMOVE_KEYWORD_SUCCESSFUL";
export const POST_REMOVE_KEYWORD_FAILED = "POST_REMOVE_KEYWORD_FAILED";