export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESSFUL = 'USER_SIGN_UP_SUCCESSFUL';
export const USER_SIGN_UP_FAILED = 'USER_SIGN_UP_FAILED';



export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESSFUL = 'USER_SIGNIN_SUCCESSFUL';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const CLEAR_ALL = "CLEAR_ALL";


export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESSFUL = 'USER_LIST_SUCCESSFUL';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESSFUL= 'USER_DETAIL_SUCCESSFUL';
export const USER_DETAIL_FAILED = 'USER_DETAIL_FAILED';

export const USER_UPDATE_PROFILE_REQUEST="USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESSFUL="USER_UPDATE_PROFILE_SUCCESSFUL";
export const USER_UPDATE_PROFILE_FAILED="USER_UPDATE_PROFILE_FAILED";
export const USER_UPDATE_PROFILE_RESET="USER_UPDATE_PROFILE_RESET";

export const USER_CONVERSATION_HISTORY_REQUEST = 'USER_CONVERSATION_HISTORY_REQUEST';
export const USER_CONVERSATION_HISTORY_SUCCESSFUL= 'USER_CONVERSATION_HISTORY_SUCCESSFUL';
export const USER_CONVERSATION_HISTORY_FAILED = 'USER_CONVERSATION_HISTORY_FAILED';

//A FULL STATISTIC REPORT OF MESSAGES
export const MESSAGE_STAT_REQUEST = 'MESSAGE_STAT_REQUEST';
export const MESSAGE_STAT_SUCCESSFUL= 'MESSAGE_STAT_SUCCESSFUL';
export const MESSAGE_STAT_FAILED = 'MESSAGE_STAT_FAILED';

export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST';
export const ADD_FRIEND_SUCCESSFUL= 'ADD_FRIEND_SUCCESSFUL';
export const ADD_FRIEND_FAILED = 'ADD_FRIEND_FAILED';

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESSFUL= 'SEARCH_USER_SUCCESSFUL';
export const SEARCH_USER_FAILED = 'SEARCH_USER_FAILED';

export const USER_DETAIL_BY_PHONE_REQUEST = 'USER_DETAIL_BY_PHONE_REQUEST';
export const USER_DETAIL_BY_PHONE_SUCCESSFUL= 'USER_DETAIL_BY_PHONE_SUCCESSFUL';
export const USER_DETAIL_BY_PHONE_FAILED = 'USER_DETAIL_BY_PHONE_FAILED';

